/**
 * @jest-environment node
 *
 * Decision verification — the edge where Solon governance becomes OrangeCat
 * reality. Two layers under test:
 *
 * 1. The Bitcoin message verifier port, pinned by a FIXED test vector
 *    generated by Solon's own signer (src/lib/bitcoin/message.ts there) — if
 *    either implementation drifts, this fails in CI.
 * 2. verifyAndApplyDecision's refusal gauntlet: unpinned voters, tampered
 *    content, unbound messages, forged outcomes and below-quorum documents
 *    must all be refused; only a fully re-verified APPROVED decision
 *    activates a policy version.
 */
import { solonVoteMessage, verifyBitcoinMessage } from '@/services/solon/bitcoin-message';
import { verifyAndApplyDecision } from '@/services/solon/decision-verify';
import { DATABASE_TABLES } from '@/config/database-tables';
import { SOLON_ORG_ID } from '@/config/solon';
import { contentHashOf } from '@/services/solon/canonical';

jest.mock('@/utils/logger', () => ({
  logger: { error: jest.fn(), warn: jest.fn(), info: jest.fn(), debug: jest.fn() },
}));

// Fixed vector generated by Solon's signMessage() with privkey 0x11…11.
const VECTOR = {
  address: '1Q1pE5vPGEEMqRcVRMbtBK842Y6Pzo6nK9',
  p2wpkh: 'bc1ql3e9pgs3mmwuwrh95fecme0s0qtn2880lsvsd5',
  message:
    'Solon vote\nsession:11111111-2222-4333-8444-555555555555\nchoice:yes\nvoter:1Q1pE5vPGEEMqRcVRMbtBK842Y6Pzo6nK9',
  signature:
    'IPTWOIU6N/j674TVg2T2ej7uRDi5AkcGVRtfY9CC04ezFV6g6um12yrjJ5W8silm95MnfPeVFjIz0HYtd6Aises=',
};

describe('verifyBitcoinMessage (pinned to Solon signer output)', () => {
  it('verifies the fixed Solon-generated vector', () => {
    const result = verifyBitcoinMessage(VECTOR.message, VECTOR.address, VECTOR.signature);
    expect(result.valid).toBe(true);
    expect(result.recoveredAddress).toBe(VECTOR.address);
  });

  it('accepts the same signature against the segwit derivation (Electrum quirk)', () => {
    expect(verifyBitcoinMessage(VECTOR.message, VECTOR.p2wpkh, VECTOR.signature).valid).toBe(true);
  });

  it('rejects a tampered message', () => {
    expect(
      verifyBitcoinMessage(VECTOR.message.replace('yes', 'no'), VECTOR.address, VECTOR.signature)
        .valid
    ).toBe(false);
  });

  it('rejects the wrong address and garbage signatures without throwing', () => {
    expect(
      verifyBitcoinMessage(VECTOR.message, '1BitcoinEaterAddressDontSendf59kuE', VECTOR.signature)
        .valid
    ).toBe(false);
    expect(verifyBitcoinMessage(VECTOR.message, VECTOR.address, 'not-base64!!').valid).toBe(false);
  });

  it('derives the canonical vote message byte-identically to Solon', () => {
    expect(
      solonVoteMessage({
        sessionId: '11111111-2222-4333-8444-555555555555',
        choice: 'yes',
        memberAddress: VECTOR.address,
      })
    ).toBe(VECTOR.message);
  });
});

// ── verifyAndApplyDecision ───────────────────────────────────────────────────

const CONTENT = { max_cat_daily_spend_btc: 0.002, max_cat_btc_per_action: 0.0005 };

function buildDocument(overrides: Record<string, unknown> = {}) {
  return {
    decision_id: '11111111-2222-4333-8444-555555555555',
    organization: { id: SOLON_ORG_ID, slug: 'orangecat' },
    proposal: {
      policyKey: 'allocation_policy',
      proposedContent: CONTENT,
      contentHash: contentHashOf(CONTENT),
      target: null,
    },
    rules: { threshold: 'SIMPLE_MAJORITY', quorumPercent: 50 },
    votes: [
      {
        member: { bitcoinAddress: VECTOR.address },
        choice: 'YES',
        signedMessage: VECTOR.message,
        signature: VECTOR.signature,
      },
    ],
    outcome: 'APPROVED',
    ...overrides,
  } as never;
}

/**
 * Table-keyed thenable mock. solon_trusted_keys resolves pinned rows;
 * allocation_policies .maybeSingle resolves per configured step (existing
 * decision check → draft lookup → latest version), inserts/updates recorded.
 */
function buildSupabase(config: {
  pinned?: { bitcoin_address: string; voting_weight: number }[];
  pinError?: { message: string } | null;
}) {
  const writes: { table: string; op: string; payload: unknown }[] = [];
  const makeChain = (table: string) => {
    const chain: Record<string, unknown> = {};
    for (const method of ['select', 'eq', 'is', 'order', 'limit', 'in', 'gte']) {
      chain[method] = jest.fn().mockReturnValue(chain);
    }
    chain.maybeSingle = jest.fn().mockResolvedValue({ data: null, error: null });
    chain.single = jest.fn().mockResolvedValue({ data: { id: 'new-row' }, error: null });
    chain.insert = jest.fn((payload: unknown) => {
      writes.push({ table, op: 'insert', payload });
      return chain;
    });
    chain.update = jest.fn((payload: unknown) => {
      writes.push({ table, op: 'update', payload });
      return chain;
    });
    chain.then = (resolve: (value: { data: unknown; error: unknown }) => unknown) => {
      if (table === DATABASE_TABLES.SOLON_TRUSTED_KEYS) {
        return Promise.resolve(
          resolve({ data: config.pinned ?? [], error: config.pinError ?? null })
        );
      }
      return Promise.resolve(resolve({ data: null, error: null }));
    };
    return chain;
  };
  return { from: jest.fn((table: string) => makeChain(table)), _writes: writes };
}

const PINNED = [{ bitcoin_address: VECTOR.address, voting_weight: 1 }];

describe('verifyAndApplyDecision', () => {
  it('refuses a non-UUID decision id before it can reach any URL', async () => {
    const supabase = buildSupabase({ pinned: PINNED });
    const result = await verifyAndApplyDecision(supabase as never, '../../admin', {
      fetchDocument: async () => buildDocument(),
    });
    expect(result.applied).toBe(false);
    expect(result.reason).toContain('not a UUID');
    expect(supabase.from).not.toHaveBeenCalled();
  });

  it('refuses when no keys are pinned', async () => {
    const supabase = buildSupabase({ pinned: [] });
    const result = await verifyAndApplyDecision(
      supabase as never,
      '11111111-2222-4333-8444-555555555555',
      {
        fetchDocument: async () => buildDocument(),
      }
    );
    expect(result.applied).toBe(false);
    expect(result.reason).toContain('no trusted keys pinned');
  });

  it('refuses a vote from an unpinned address', async () => {
    const supabase = buildSupabase({
      pinned: [{ bitcoin_address: '1SomeoneElse', voting_weight: 1 }],
    });
    const result = await verifyAndApplyDecision(
      supabase as never,
      '11111111-2222-4333-8444-555555555555',
      {
        fetchDocument: async () => buildDocument(),
      }
    );
    expect(result.applied).toBe(false);
    expect(result.reason).toContain('unpinned');
  });

  it('refuses tampered content (hash mismatch)', async () => {
    const supabase = buildSupabase({ pinned: PINNED });
    const doc = buildDocument();
    (doc as { proposal: { proposedContent: unknown } }).proposal.proposedContent = {
      max_cat_daily_spend_btc: 100,
      max_cat_btc_per_action: 100,
    };
    const result = await verifyAndApplyDecision(
      supabase as never,
      '11111111-2222-4333-8444-555555555555',
      {
        fetchDocument: async () => doc,
      }
    );
    expect(result.applied).toBe(false);
    expect(result.reason).toContain('content hash mismatch');
  });

  it('refuses a signed message that does not bind this session', async () => {
    const supabase = buildSupabase({ pinned: PINNED });
    const result = await verifyAndApplyDecision(
      supabase as never,
      '99999999-2222-4333-8444-555555555555',
      {
        fetchDocument: async () =>
          buildDocument({ decision_id: '99999999-2222-4333-8444-555555555555' }),
      }
    );
    expect(result.applied).toBe(false);
    expect(result.reason).toContain('does not bind');
  });

  it('refuses a claimed APPROVED outcome the recomputed tally does not support', async () => {
    const supabase = buildSupabase({
      // Second pinned member doubles eligible weight; single yes still passes
      // majority but we flip the vote to NO via a re-signed... instead: claim
      // approved with only an abstain-equivalent — here, no decisive votes.
      pinned: PINNED,
    });
    const doc = buildDocument({ votes: [] });
    const result = await verifyAndApplyDecision(
      supabase as never,
      '11111111-2222-4333-8444-555555555555',
      {
        fetchDocument: async () => doc,
      }
    );
    expect(result.applied).toBe(false);
    expect(result.reason).toContain('no votes');
  });

  it('refuses when verified votes fall below quorum of the pinned electorate', async () => {
    const supabase = buildSupabase({
      pinned: [
        ...PINNED,
        { bitcoin_address: '1Absent1', voting_weight: 1 },
        { bitcoin_address: '1Absent2', voting_weight: 1 },
      ],
    });
    // 1 of 3 weight cast = 33% < 50% quorum.
    const result = await verifyAndApplyDecision(
      supabase as never,
      '11111111-2222-4333-8444-555555555555',
      {
        fetchDocument: async () => buildDocument(),
      }
    );
    expect(result.applied).toBe(false);
    expect(result.reason).toContain('quorum');
  });

  it('refuses non-APPROVED outcomes without touching the database', async () => {
    const supabase = buildSupabase({ pinned: PINNED });
    const result = await verifyAndApplyDecision(
      supabase as never,
      '11111111-2222-4333-8444-555555555555',
      {
        fetchDocument: async () => buildDocument({ outcome: 'REJECTED' }),
      }
    );
    expect(result.applied).toBe(false);
    expect(supabase._writes).toHaveLength(0);
  });

  it('applies a fully verified decision: records the version and activates it', async () => {
    const supabase = buildSupabase({ pinned: PINNED });
    // activateVersion loads the inserted row: make allocation_policies
    // maybeSingle return the freshly inserted draft on later calls.
    let policyReads = 0;
    const origFrom = supabase.from;
    supabase.from = jest.fn((table: string) => {
      const chain = origFrom(table) as Record<string, unknown> & {
        maybeSingle: jest.Mock;
      };
      if (table === DATABASE_TABLES.ALLOCATION_POLICIES) {
        chain.maybeSingle = jest.fn(() => {
          policyReads += 1;
          // reads: 1=existing-decision check, 2=draft-by-hash, 3=latest version,
          // 4=activateVersion row load.
          if (policyReads === 3) {
            return Promise.resolve({ data: { version: 1 }, error: null });
          }
          if (policyReads === 4) {
            return Promise.resolve({
              data: {
                id: 'new-row',
                policy_key: 'allocation_policy',
                version: 2,
                status: 'draft',
                verified_at: new Date().toISOString(),
                solon_decision_id: '11111111-2222-4333-8444-555555555555',
              },
              error: null,
            });
          }
          return Promise.resolve({ data: null, error: null });
        });
      }
      return chain;
    }) as never;

    const result = await verifyAndApplyDecision(
      supabase as never,
      '11111111-2222-4333-8444-555555555555',
      {
        fetchDocument: async () => buildDocument(),
      }
    );

    expect(result).toEqual({ applied: true, version: 2 });
    const inserted = supabase._writes.find(w => w.op === 'insert');
    expect(inserted).toBeDefined();
    expect((inserted!.payload as { verified_at: string }).verified_at).toBeTruthy();
    // Activation writes: superseded (none active in this mock, still issued) + active.
    const statusUpdates = supabase._writes
      .filter(w => w.op === 'update')
      .map(w => (w.payload as { status?: string }).status)
      .filter(Boolean);
    expect(statusUpdates).toContain('active');
  });
});
