// CORRECTED TypeScript types for OrangeCat database
// Generated by analyzing live database schema
// Date: 2025-12-19

// NOTE:
// This module also re-exports higher-level application models so that
// imports from `@/types/database` remain the single source of truth
// for profile- and project-related types across the app.

import type { Profile as AppProfile } from './profile';
import type { Project as AppProject } from './project';
import type { ProfileData } from '../lib/validation';

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string | null;
          name: string | null;
          bio: string | null;
          email: string | null;
          display_name: string | null;
          // Location fields
          location: string | null;
          location_search: string | null;
          location_country: string | null;
          location_city: string | null;
          location_zip: string | null;
          latitude: number | null;
          longitude: number | null;
          timezone: string | null;
          // Media fields
          avatar_url: string | null;
          banner_url: string | null;
          cover_image_url: string | null;
          website: string | null;
          // Contact
          contact_email: string | null;
          phone: string | null;
          // Social
          social_links: Json | null;
          follower_count: number | null;
          following_count: number | null;
          profile_views: number | null;
          // Crypto
          bitcoin_address: string | null;
          lightning_address: string | null;
          bitcoin_public_key: string | null;
          lightning_node_id: string | null;
          bitcoin_balance: number | null;
          lightning_balance: number | null;
          // Status & Verification
          verification_status: string | null;
          verification_level: string | null;
          is_verified: boolean | null;
          kyc_status: string | null;
          verification_data: Json | null;
          verification_badge: string | null;
          status: string | null;
          // Activity
          campaign_count: number | null;
          total_raised: number | null;
          total_donated: number | null;
          last_login_at: string | null;
          last_active_at: string | null;
          login_count: number | null;
          // Preferences
          language: string | null;
          currency: string | null;
          theme_preferences: Json | null;
          custom_css: string | null;
          profile_color: string | null;
          profile_badges: Json | null;
          payment_preferences: Json | null;
          preferences: Json | null;
          privacy_settings: Json | null;
          metadata: Json | null;
          // Onboarding
          onboarding_completed: boolean | null;
          profile_completed_at: string | null;
          terms_accepted_at: string | null;
          privacy_policy_accepted_at: string | null;
          two_factor_enabled: boolean | null;
          // Timestamps
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username?: string | null;
          name?: string | null;
          bio?: string | null;
          email?: string | null;
          display_name?: string | null;
          // Location fields
          location?: string | null;
          location_search?: string | null;
          location_country?: string | null;
          location_city?: string | null;
          location_zip?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          timezone?: string | null;
          // Media fields
          avatar_url?: string | null;
          banner_url?: string | null;
          cover_image_url?: string | null;
          website?: string | null;
          // Contact
          contact_email?: string | null;
          phone?: string | null;
          // Social
          social_links?: Json | null;
          follower_count?: number | null;
          following_count?: number | null;
          profile_views?: number | null;
          // Crypto
          bitcoin_address?: string | null;
          lightning_address?: string | null;
          bitcoin_public_key?: string | null;
          lightning_node_id?: string | null;
          bitcoin_balance?: number | null;
          lightning_balance?: number | null;
          // Status & Verification
          verification_status?: string | null;
          verification_level?: string | null;
          is_verified?: boolean | null;
          kyc_status?: string | null;
          verification_data?: Json | null;
          verification_badge?: string | null;
          status?: string | null;
          // Activity
          campaign_count?: number | null;
          total_raised?: number | null;
          total_donated?: number | null;
          last_login_at?: string | null;
          last_active_at?: string | null;
          login_count?: number | null;
          // Preferences
          language?: string | null;
          currency?: string | null;
          theme_preferences?: Json | null;
          custom_css?: string | null;
          profile_color?: string | null;
          profile_badges?: Json | null;
          payment_preferences?: Json | null;
          preferences?: Json | null;
          privacy_settings?: Json | null;
          metadata?: Json | null;
          // Onboarding
          onboarding_completed?: boolean | null;
          profile_completed_at?: string | null;
          terms_accepted_at?: string | null;
          privacy_policy_accepted_at?: string | null;
          two_factor_enabled?: boolean | null;
          // Timestamps
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string | null;
          name?: string | null;
          bio?: string | null;
          email?: string | null;
          display_name?: string | null;
          // Location fields
          location?: string | null;
          location_search?: string | null;
          location_country?: string | null;
          location_city?: string | null;
          location_zip?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          timezone?: string | null;
          // Media fields
          avatar_url?: string | null;
          banner_url?: string | null;
          cover_image_url?: string | null;
          website?: string | null;
          // Contact
          contact_email?: string | null;
          phone?: string | null;
          // Social
          social_links?: Json | null;
          follower_count?: number | null;
          following_count?: number | null;
          profile_views?: number | null;
          // Crypto
          bitcoin_address?: string | null;
          lightning_address?: string | null;
          bitcoin_public_key?: string | null;
          lightning_node_id?: string | null;
          bitcoin_balance?: number | null;
          lightning_balance?: number | null;
          // Status & Verification
          verification_status?: string | null;
          verification_level?: string | null;
          is_verified?: boolean | null;
          kyc_status?: string | null;
          verification_data?: Json | null;
          verification_badge?: string | null;
          status?: string | null;
          // Activity
          campaign_count?: number | null;
          total_raised?: number | null;
          total_donated?: number | null;
          last_login_at?: string | null;
          last_active_at?: string | null;
          login_count?: number | null;
          // Preferences
          language?: string | null;
          currency?: string | null;
          theme_preferences?: Json | null;
          custom_css?: string | null;
          profile_color?: string | null;
          profile_badges?: Json | null;
          payment_preferences?: Json | null;
          preferences?: Json | null;
          privacy_settings?: Json | null;
          metadata?: Json | null;
          // Onboarding
          onboarding_completed?: boolean | null;
          profile_completed_at?: string | null;
          terms_accepted_at?: string | null;
          privacy_policy_accepted_at?: string | null;
          two_factor_enabled?: boolean | null;
          // Timestamps
          created_at?: string;
          updated_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          title: string | null;
          is_group: boolean;
          conversation_type: string | null;
          description: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          last_message_at: string | null;
          last_message_preview: string | null;
          last_message_sender_id: string | null;
        };
        Insert: {
          id?: string;
          title?: string | null;
          is_group?: boolean;
          conversation_type?: string | null;
          description?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          last_message_at?: string | null;
          last_message_preview?: string | null;
          last_message_sender_id?: string | null;
        };
        Update: {
          id?: string;
          title?: string | null;
          is_group?: boolean;
          conversation_type?: string | null;
          description?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          last_message_at?: string | null;
          last_message_preview?: string | null;
          last_message_sender_id?: string | null;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          content: string;
          message_type: string;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
          edited_at: string | null;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id: string;
          content: string;
          message_type?: string;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
          edited_at?: string | null;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender_id?: string;
          content?: string;
          message_type?: string;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
          edited_at?: string | null;
        };
      };
      conversation_participants: {
        Row: {
          id: string;
          conversation_id: string;
          user_id: string;
          role: string;
          joined_at: string;
          last_read_at: string | null;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          user_id: string;
          role?: string;
          joined_at?: string;
          last_read_at?: string | null;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          user_id?: string;
          role?: string;
          joined_at?: string;
          last_read_at?: string | null;
          is_active?: boolean;
        };
      };
      typing_indicators: {
        Row: {
          id: string;
          conversation_id: string;
          user_id: string;
          started_at: string;
          expires_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          user_id: string;
          started_at?: string;
          expires_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          user_id?: string;
          started_at?: string;
          expires_at?: string;
        };
      };
      user_presence: {
        Row: {
          user_id: string;
          status: string;
          last_seen_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          status?: string;
          last_seen_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          status?: string;
          last_seen_at?: string;
          updated_at?: string;
        };
      };

      /**
       * The following tables are added with permissive typings to restore
       * type-safety for Supabase operations that were previously resolving
       * to `never` due to missing table definitions. These can be tightened
       * over time but are sufficient for compile-time safety.
       */
      user_products: {
        Row: {
          [key: string]: any;
        };
        Insert: {
          [key: string]: any;
        };
        Update: {
          [key: string]: any;
        };
      };

      user_services: {
        Row: {
          [key: string]: any;
        };
        Insert: {
          [key: string]: any;
        };
        Update: {
          [key: string]: any;
        };
      };

      circles: {
        Row: {
          [key: string]: any;
        };
        Insert: {
          [key: string]: any;
        };
        Update: {
          [key: string]: any;
        };
      };

      organizations: {
        Row: {
          [key: string]: any;
        };
        Insert: {
          [key: string]: any;
        };
        Update: {
          [key: string]: any;
        };
      };
    };
    Views: {
      message_details: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          content: string;
          message_type: string;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
          edited_at: string | null;
          sender_username: string | null;
          sender_name: string | null;
          sender_avatar_url: string | null;
        };
      };
      conversation_details: {
        Row: {
          id: string;
          title: string | null;
          is_group: boolean;
          conversation_type: string | null;
          last_message_at: string | null;
          last_message_preview: string | null;
          last_message_sender_id: string | null;
          created_at: string;
          updated_at: string;
          participant_ids: string[];
          participant_usernames: string[];
          participant_names: string[];
          participant_avatars: string[];
          unread_count: number;
        };
      };
    };
    Functions: {
      get_total_unread_count: {
        Args: { p_user_id: string };
        Returns: number;
      };
      set_typing_indicator: {
        Args: { p_conversation_id: string; p_user_id: string; p_is_typing: boolean };
        Returns: void;
      };
      update_presence: {
        Args: { p_status: string };
        Returns: void;
      };
      send_message: {
        Args: { p_conversation_id: string; p_sender_id: string; p_content: string };
        Returns: string;
      };
      get_user_conversations: {
        Args: { p_user_id: string };
        Returns: unknown[];
      };
      create_group_conversation: {
        Args: { p_created_by: string; p_participant_ids: string[]; p_title: string | null };
        Returns: string;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// ---------------------------------------------------------------------------
// High-level application models
// ---------------------------------------------------------------------------

// Unified profile model used across the application (backed by `profiles`)
// Note: Extended with email field from database schema

// Form data shape for profile editing flows (from Zod profile schema)
export type ProfileFormData = ProfileData;

// Project view model used by dashboard and timeline components
export type Project = AppProject;

// Commerce entity types
export type UserProduct = Database['public']['Tables']['user_products']['Row'];
export type UserService = Database['public']['Tables']['user_services']['Row'];
// UserCause type - using any for now since table may not be fully defined
export type UserCause = Record<string, any>;

// Extended Profile type that includes email from database
export type Profile = AppProfile & {
  email?: string | null;
};
