// CORRECTED TypeScript types for OrangeCat database
// Generated by analyzing live database schema
// Date: 2025-12-19

// NOTE:
// This module also re-exports higher-level application models so that
// imports from `@/types/database` remain the single source of truth
// for profile- and project-related types across the app.

import type { Profile as AppProfile } from './profile';
import type { Project as AppProject } from './project';
import type { ProfileData } from '../lib/validation';

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string | null;
          name: string | null;
          bio: string | null;
          email: string | null;
          // Note: display_name should be migrated to name - see migration 20250130000006
          display_name?: string | null; // @deprecated - use 'name' instead
          // Location fields
          location: string | null;
          location_search: string | null;
          location_country: string | null;
          location_city: string | null;
          location_zip: string | null;
          latitude: number | null;
          longitude: number | null;
          timezone: string | null;
          // Media fields
          avatar_url: string | null;
          banner_url: string | null;
          cover_image_url: string | null;
          website: string | null;
          // Contact
          contact_email: string | null;
          phone: string | null;
          // Social
          social_links: Json | null;
          follower_count: number | null;
          following_count: number | null;
          profile_views: number | null;
          // Crypto
          bitcoin_address: string | null;
          lightning_address: string | null;
          bitcoin_public_key: string | null;
          lightning_node_id: string | null;
          bitcoin_balance: number | null;
          lightning_balance: number | null;
          // Status & Verification
          verification_status: string | null;
          verification_level: string | null;
          is_verified: boolean | null;
          kyc_status: string | null;
          verification_data: Json | null;
          verification_badge: string | null;
          status: string | null;
          // Activity
          campaign_count: number | null;
          total_raised: number | null;
          total_donated: number | null;
          last_login_at: string | null;
          last_active_at: string | null;
          login_count: number | null;
          // Preferences
          language: string | null;
          currency: string | null;
          theme_preferences: Json | null;
          custom_css: string | null;
          profile_color: string | null;
          profile_badges: Json | null;
          payment_preferences: Json | null;
          preferences: Json | null;
          privacy_settings: Json | null;
          metadata: Json | null;
          // Onboarding
          onboarding_completed: boolean | null;
          profile_completed_at: string | null;
          terms_accepted_at: string | null;
          privacy_policy_accepted_at: string | null;
          two_factor_enabled: boolean | null;
          // Timestamps
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username?: string | null;
          name?: string | null;
          bio?: string | null;
          email?: string | null;
          // Note: display_name should be migrated to name - see migration 20250130000006
          display_name?: string | null; // @deprecated - use 'name' instead
          // Location fields
          location?: string | null;
          location_search?: string | null;
          location_country?: string | null;
          location_city?: string | null;
          location_zip?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          timezone?: string | null;
          // Media fields
          avatar_url?: string | null;
          banner_url?: string | null;
          cover_image_url?: string | null;
          website?: string | null;
          // Contact
          contact_email?: string | null;
          phone?: string | null;
          // Social
          social_links?: Json | null;
          follower_count?: number | null;
          following_count?: number | null;
          profile_views?: number | null;
          // Crypto
          bitcoin_address?: string | null;
          lightning_address?: string | null;
          bitcoin_public_key?: string | null;
          lightning_node_id?: string | null;
          bitcoin_balance?: number | null;
          lightning_balance?: number | null;
          // Status & Verification
          verification_status?: string | null;
          verification_level?: string | null;
          is_verified?: boolean | null;
          kyc_status?: string | null;
          verification_data?: Json | null;
          verification_badge?: string | null;
          status?: string | null;
          // Activity
          campaign_count?: number | null;
          total_raised?: number | null;
          total_donated?: number | null;
          last_login_at?: string | null;
          last_active_at?: string | null;
          login_count?: number | null;
          // Preferences
          language?: string | null;
          currency?: string | null;
          theme_preferences?: Json | null;
          custom_css?: string | null;
          profile_color?: string | null;
          profile_badges?: Json | null;
          payment_preferences?: Json | null;
          preferences?: Json | null;
          privacy_settings?: Json | null;
          metadata?: Json | null;
          // Onboarding
          onboarding_completed?: boolean | null;
          profile_completed_at?: string | null;
          terms_accepted_at?: string | null;
          privacy_policy_accepted_at?: string | null;
          two_factor_enabled?: boolean | null;
          // Timestamps
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string | null;
          name?: string | null;
          bio?: string | null;
          email?: string | null;
          display_name?: string | null;
          // Location fields
          location?: string | null;
          location_search?: string | null;
          location_country?: string | null;
          location_city?: string | null;
          location_zip?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          timezone?: string | null;
          // Media fields
          avatar_url?: string | null;
          banner_url?: string | null;
          cover_image_url?: string | null;
          website?: string | null;
          // Contact
          contact_email?: string | null;
          phone?: string | null;
          // Social
          social_links?: Json | null;
          follower_count?: number | null;
          following_count?: number | null;
          profile_views?: number | null;
          // Crypto
          bitcoin_address?: string | null;
          lightning_address?: string | null;
          bitcoin_public_key?: string | null;
          lightning_node_id?: string | null;
          bitcoin_balance?: number | null;
          lightning_balance?: number | null;
          // Status & Verification
          verification_status?: string | null;
          verification_level?: string | null;
          is_verified?: boolean | null;
          kyc_status?: string | null;
          verification_data?: Json | null;
          verification_badge?: string | null;
          status?: string | null;
          // Activity
          campaign_count?: number | null;
          total_raised?: number | null;
          total_donated?: number | null;
          last_login_at?: string | null;
          last_active_at?: string | null;
          login_count?: number | null;
          // Preferences
          language?: string | null;
          currency?: string | null;
          theme_preferences?: Json | null;
          custom_css?: string | null;
          profile_color?: string | null;
          profile_badges?: Json | null;
          payment_preferences?: Json | null;
          preferences?: Json | null;
          privacy_settings?: Json | null;
          metadata?: Json | null;
          // Onboarding
          onboarding_completed?: boolean | null;
          profile_completed_at?: string | null;
          terms_accepted_at?: string | null;
          privacy_policy_accepted_at?: string | null;
          two_factor_enabled?: boolean | null;
          // Timestamps
          created_at?: string;
          updated_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          title: string | null;
          is_group: boolean;
          conversation_type: string | null;
          description: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          last_message_at: string | null;
          last_message_preview: string | null;
          last_message_sender_id: string | null;
        };
        Insert: {
          id?: string;
          title?: string | null;
          is_group?: boolean;
          conversation_type?: string | null;
          description?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          last_message_at?: string | null;
          last_message_preview?: string | null;
          last_message_sender_id?: string | null;
        };
        Update: {
          id?: string;
          title?: string | null;
          is_group?: boolean;
          conversation_type?: string | null;
          description?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          last_message_at?: string | null;
          last_message_preview?: string | null;
          last_message_sender_id?: string | null;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          content: string;
          message_type: string;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
          edited_at: string | null;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id: string;
          content: string;
          message_type?: string;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
          edited_at?: string | null;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender_id?: string;
          content?: string;
          message_type?: string;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
          edited_at?: string | null;
        };
      };
      conversation_participants: {
        Row: {
          id: string;
          conversation_id: string;
          user_id: string;
          role: string;
          joined_at: string;
          last_read_at: string | null;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          user_id: string;
          role?: string;
          joined_at?: string;
          last_read_at?: string | null;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          user_id?: string;
          role?: string;
          joined_at?: string;
          last_read_at?: string | null;
          is_active?: boolean;
        };
      };
      typing_indicators: {
        Row: {
          id: string;
          conversation_id: string;
          user_id: string;
          started_at: string;
          expires_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          user_id: string;
          started_at?: string;
          expires_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          user_id?: string;
          started_at?: string;
          expires_at?: string;
        };
      };
      user_presence: {
        Row: {
          user_id: string;
          status: string;
          last_seen_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          status?: string;
          last_seen_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          status?: string;
          last_seen_at?: string;
          updated_at?: string;
        };
      };

      /**
       * The following tables are added with permissive typings to restore
       * type-safety for Supabase operations that were previously resolving
       * to `never` due to missing table definitions. These can be tightened
       * over time but are sufficient for compile-time safety.
       */
      user_products: {
        Row: {
          [key: string]: any;
        };
        Insert: {
          [key: string]: any;
        };
        Update: {
          [key: string]: any;
        };
      };

      user_services: {
        Row: {
          [key: string]: any;
        };
        Insert: {
          [key: string]: any;
        };
        Update: {
          [key: string]: any;
        };
      };

      user_causes: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          cause_category: string;
          goal_sats: number | null;
          total_raised_sats: number;
          currency: string;
          bitcoin_address: string | null;
          lightning_address: string | null;
          distribution_rules: any;
          beneficiaries: any[];
          status: 'draft' | 'active' | 'completed' | 'paused';
          created_at: string;
          updated_at: string;
          [key: string]: any;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          cause_category: string;
          goal_sats?: number | null;
          total_raised_sats?: number;
          currency?: string;
          bitcoin_address?: string | null;
          lightning_address?: string | null;
          distribution_rules?: any;
          beneficiaries?: any[];
          status?: 'draft' | 'active' | 'completed' | 'paused';
          created_at?: string;
          updated_at?: string;
          [key: string]: any;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          cause_category?: string;
          goal_sats?: number | null;
          total_raised_sats?: number;
          currency?: string;
          bitcoin_address?: string | null;
          lightning_address?: string | null;
          distribution_rules?: any;
          beneficiaries?: any[];
          status?: 'draft' | 'active' | 'completed' | 'paused';
          created_at?: string;
          updated_at?: string;
          [key: string]: any;
        };
      };

      circles: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          category: string;
          visibility: 'public' | 'private' | 'hidden';
          max_members: number | null;
          member_approval: 'auto' | 'manual' | 'invite';
          location_restricted: boolean;
          location_radius_km: number | null;
          bitcoin_address: string | null;
          wallet_purpose: string | null;
          contribution_required: boolean;
          contribution_amount: number | null;
          activity_level: 'casual' | 'regular' | 'intensive';
          meeting_frequency: 'none' | 'weekly' | 'monthly' | 'quarterly';
          enable_projects: boolean;
          enable_events: boolean;
          enable_discussions: boolean;
          require_member_intro: boolean;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          category: string;
          visibility?: 'public' | 'private' | 'hidden';
          max_members?: number | null;
          member_approval?: 'auto' | 'manual' | 'invite';
          location_restricted?: boolean;
          location_radius_km?: number | null;
          bitcoin_address?: string | null;
          wallet_purpose?: string | null;
          contribution_required?: boolean;
          contribution_amount?: number | null;
          activity_level?: 'casual' | 'regular' | 'intensive';
          meeting_frequency?: 'none' | 'weekly' | 'monthly' | 'quarterly';
          enable_projects?: boolean;
          enable_events?: boolean;
          enable_discussions?: boolean;
          require_member_intro?: boolean;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          category?: string;
          visibility?: 'public' | 'private' | 'hidden';
          max_members?: number | null;
          member_approval?: 'auto' | 'manual' | 'invite';
          location_restricted?: boolean;
          location_radius_km?: number | null;
          bitcoin_address?: string | null;
          wallet_purpose?: string | null;
          contribution_required?: boolean;
          contribution_amount?: number | null;
          activity_level?: 'casual' | 'regular' | 'intensive';
          meeting_frequency?: 'none' | 'weekly' | 'monthly' | 'quarterly';
          enable_projects?: boolean;
          enable_events?: boolean;
          enable_discussions?: boolean;
          require_member_intro?: boolean;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };

      circle_members: {
        Row: {
          id: string;
          circle_id: string;
          user_id: string;
          role: 'owner' | 'admin' | 'moderator' | 'member';
          status: 'active' | 'pending' | 'suspended';
          joined_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          circle_id: string;
          user_id: string;
          role?: 'owner' | 'admin' | 'moderator' | 'member';
          status?: 'active' | 'pending' | 'suspended';
          joined_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          circle_id?: string;
          user_id?: string;
          role?: 'owner' | 'admin' | 'moderator' | 'member';
          status?: 'active' | 'pending' | 'suspended';
          joined_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };

      circle_discussion_categories: {
        Row: {
          id: string;
          circle_id: string;
          name: string;
          description: string | null;
          is_default: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          circle_id: string;
          name: string;
          description?: string | null;
          is_default?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          circle_id?: string;
          name?: string;
          description?: string | null;
          is_default?: boolean;
          created_at?: string;
        };
      };

      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          type: string;
          governance_model: string | null;
          treasury_address: string | null;
          is_public: boolean;
          transparency_score: number | null;
          created_by: string;
          created_at: string;
          updated_at: string;
          [key: string]: any;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          type?: string;
          governance_model?: string | null;
          treasury_address?: string | null;
          is_public?: boolean;
          transparency_score?: number | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          [key: string]: any;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          type?: string;
          governance_model?: string | null;
          treasury_address?: string | null;
          is_public?: boolean;
          transparency_score?: number | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          [key: string]: any;
        };
      };

      ai_assistants: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          category: string | null;
          tags: string[];
          avatar_url: string | null;
          system_prompt: string;
          welcome_message: string | null;
          personality_traits: string[] | null;
          knowledge_base_urls: string[] | null;
          model_preference: string;
          max_tokens_per_response: number;
          temperature: number;
          compute_provider_type: 'api' | 'self_hosted' | 'community';
          compute_provider_id: string | null;
          api_provider: string | null;
          pricing_model: 'per_message' | 'per_token' | 'subscription' | 'free';
          price_per_message_sats: number;
          price_per_1k_tokens_sats: number;
          subscription_price_sats: number;
          free_messages_per_day: number;
          status: 'draft' | 'active' | 'paused' | 'archived';
          is_public: boolean;
          is_featured: boolean;
          total_conversations: number;
          total_messages: number;
          total_tokens_used: number;
          total_revenue_sats: number;
          average_rating: number | null;
          total_ratings: number;
          lightning_address: string | null;
          bitcoin_address: string | null;
          created_at: string;
          updated_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          category?: string | null;
          tags?: string[];
          avatar_url?: string | null;
          system_prompt: string;
          welcome_message?: string | null;
          personality_traits?: string[] | null;
          knowledge_base_urls?: string[] | null;
          model_preference?: string;
          max_tokens_per_response?: number;
          temperature?: number;
          compute_provider_type?: 'api' | 'self_hosted' | 'community';
          compute_provider_id?: string | null;
          api_provider?: string | null;
          pricing_model?: 'per_message' | 'per_token' | 'subscription' | 'free';
          price_per_message_sats?: number;
          price_per_1k_tokens_sats?: number;
          subscription_price_sats?: number;
          free_messages_per_day?: number;
          status?: 'draft' | 'active' | 'paused' | 'archived';
          is_public?: boolean;
          is_featured?: boolean;
          total_conversations?: number;
          total_messages?: number;
          total_tokens_used?: number;
          total_revenue_sats?: number;
          average_rating?: number | null;
          total_ratings?: number;
          lightning_address?: string | null;
          bitcoin_address?: string | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          category?: string | null;
          tags?: string[];
          avatar_url?: string | null;
          system_prompt?: string;
          welcome_message?: string | null;
          personality_traits?: string[] | null;
          knowledge_base_urls?: string[] | null;
          model_preference?: string;
          max_tokens_per_response?: number;
          temperature?: number;
          compute_provider_type?: 'api' | 'self_hosted' | 'community';
          compute_provider_id?: string | null;
          api_provider?: string | null;
          pricing_model?: 'per_message' | 'per_token' | 'subscription' | 'free';
          price_per_message_sats?: number;
          price_per_1k_tokens_sats?: number;
          subscription_price_sats?: number;
          free_messages_per_day?: number;
          status?: 'draft' | 'active' | 'paused' | 'archived';
          is_public?: boolean;
          is_featured?: boolean;
          total_conversations?: number;
          total_messages?: number;
          total_tokens_used?: number;
          total_revenue_sats?: number;
          average_rating?: number | null;
          total_ratings?: number;
          lightning_address?: string | null;
          bitcoin_address?: string | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
      };
    };
    Views: {
      message_details: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          content: string;
          message_type: string;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
          edited_at: string | null;
          sender_username: string | null;
          sender_name: string | null;
          sender_avatar_url: string | null;
        };
      };
      conversation_details: {
        Row: {
          id: string;
          title: string | null;
          is_group: boolean;
          conversation_type: string | null;
          last_message_at: string | null;
          last_message_preview: string | null;
          last_message_sender_id: string | null;
          created_at: string;
          updated_at: string;
          participant_ids: string[];
          participant_usernames: string[];
          participant_names: string[];
          participant_avatars: string[];
          unread_count: number;
        };
      };
    };
    Functions: {
      get_total_unread_count: {
        Args: { p_user_id: string };
        Returns: number;
      };
      set_typing_indicator: {
        Args: { p_conversation_id: string; p_user_id: string; p_is_typing: boolean };
        Returns: void;
      };
      update_presence: {
        Args: { p_status: string };
        Returns: void;
      };
      send_message: {
        Args: { p_conversation_id: string; p_sender_id: string; p_content: string };
        Returns: string;
      };
      get_user_conversations: {
        Args: { p_user_id: string };
        Returns: unknown[];
      };
      create_group_conversation: {
        Args: { p_created_by: string; p_participant_ids: string[]; p_title: string | null };
        Returns: string;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// ---------------------------------------------------------------------------
// High-level application models
// ---------------------------------------------------------------------------

// Unified profile model used across the application (backed by `profiles`)
// Note: Extended with email field from database schema

// Form data shape for profile editing flows (from Zod profile schema)
export type ProfileFormData = ProfileData;

// Project view model used by dashboard and timeline components
export type Project = AppProject;

// Commerce entity types - include required BaseEntity fields for type safety
// The database uses [key: string]: any but we need id and title for entity list components
export type UserProduct = Database['public']['Tables']['user_products']['Row'] & {
  id: string;
  title: string;
  description?: string | null;
  thumbnail_url?: string | null;
  status?: string;
  price_sats?: number;
  currency?: string;
  images?: string[];
};

export type UserService = Database['public']['Tables']['user_services']['Row'] & {
  id: string;
  title: string;
  description?: string | null;
  thumbnail_url?: string | null;
  status?: string;
  category?: string;
  hourly_rate_sats?: number;
  fixed_price_sats?: number;
  service_location_type?: string;
};

export type UserCause = {
  id: string;
  user_id: string;
  title: string;
  description?: string | null;
  thumbnail_url?: string | null;
  cause_category: string;
  goal_sats?: number | null;
  total_raised_sats: number;
  currency?: string;
  bitcoin_address?: string | null;
  lightning_address?: string | null;
  distribution_rules?: any;
  beneficiaries?: any[];
  status: 'draft' | 'active' | 'completed' | 'paused';
  created_at: string;
  updated_at?: string;
  [key: string]: any; // Allow additional properties
};

// Extended Profile type that includes email from database
export type Profile = AppProfile & {
  email?: string | null;
};

// AI Assistant type for dashboard and entity components
export type AIAssistant = Database['public']['Tables']['ai_assistants']['Row'];
