// CORRECTED TypeScript types for OrangeCat database
// Generated by analyzing live database schema
// Date: 2025-12-19

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string | null;
          name: string | null;
          bio: string | null;
          email: string | null;
          display_name: string | null;
          // Location fields
          location: string | null;
          location_search: string | null;
          location_country: string | null;
          location_city: string | null;
          location_zip: string | null;
          latitude: number | null;
          longitude: number | null;
          timezone: string | null;
          // Media fields
          avatar_url: string | null;
          banner_url: string | null;
          cover_image_url: string | null;
          website: string | null;
          // Contact
          contact_email: string | null;
          phone: string | null;
          // Social
          social_links: Json | null;
          follower_count: number | null;
          following_count: number | null;
          profile_views: number | null;
          // Crypto
          bitcoin_address: string | null;
          lightning_address: string | null;
          bitcoin_public_key: string | null;
          lightning_node_id: string | null;
          bitcoin_balance: number | null;
          lightning_balance: number | null;
          // Status & Verification
          verification_status: string | null;
          verification_level: string | null;
          is_verified: boolean | null;
          kyc_status: string | null;
          verification_data: Json | null;
          verification_badge: string | null;
          status: string | null;
          // Activity
          campaign_count: number | null;
          total_raised: number | null;
          total_donated: number | null;
          last_login_at: string | null;
          last_active_at: string | null;
          login_count: number | null;
          // Preferences
          language: string | null;
          currency: string | null;
          theme_preferences: Json | null;
          custom_css: string | null;
          profile_color: string | null;
          profile_badges: Json | null;
          payment_preferences: Json | null;
          preferences: Json | null;
          privacy_settings: Json | null;
          metadata: Json | null;
          // Onboarding
          onboarding_completed: boolean | null;
          profile_completed_at: string | null;
          terms_accepted_at: string | null;
          privacy_policy_accepted_at: string | null;
          two_factor_enabled: boolean | null;
          // Timestamps
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username?: string | null;
          name?: string | null;
          bio?: string | null;
          email?: string | null;
          display_name?: string | null;
          // Location fields
          location?: string | null;
          location_search?: string | null;
          location_country?: string | null;
          location_city?: string | null;
          location_zip?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          timezone?: string | null;
          // Media fields
          avatar_url?: string | null;
          banner_url?: string | null;
          cover_image_url?: string | null;
          website?: string | null;
          // Contact
          contact_email?: string | null;
          phone?: string | null;
          // Social
          social_links?: Json | null;
          follower_count?: number | null;
          following_count?: number | null;
          profile_views?: number | null;
          // Crypto
          bitcoin_address?: string | null;
          lightning_address?: string | null;
          bitcoin_public_key?: string | null;
          lightning_node_id?: string | null;
          bitcoin_balance?: number | null;
          lightning_balance?: number | null;
          // Status & Verification
          verification_status?: string | null;
          verification_level?: string | null;
          is_verified?: boolean | null;
          kyc_status?: string | null;
          verification_data?: Json | null;
          verification_badge?: string | null;
          status?: string | null;
          // Activity
          campaign_count?: number | null;
          total_raised?: number | null;
          total_donated?: number | null;
          last_login_at?: string | null;
          last_active_at?: string | null;
          login_count?: number | null;
          // Preferences
          language?: string | null;
          currency?: string | null;
          theme_preferences?: Json | null;
          custom_css?: string | null;
          profile_color?: string | null;
          profile_badges?: Json | null;
          payment_preferences?: Json | null;
          preferences?: Json | null;
          privacy_settings?: Json | null;
          metadata?: Json | null;
          // Onboarding
          onboarding_completed?: boolean | null;
          profile_completed_at?: string | null;
          terms_accepted_at?: string | null;
          privacy_policy_accepted_at?: string | null;
          two_factor_enabled?: boolean | null;
          // Timestamps
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string | null;
          name?: string | null;
          bio?: string | null;
          email?: string | null;
          display_name?: string | null;
          // Location fields
          location?: string | null;
          location_search?: string | null;
          location_country?: string | null;
          location_city?: string | null;
          location_zip?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          timezone?: string | null;
          // Media fields
          avatar_url?: string | null;
          banner_url?: string | null;
          cover_image_url?: string | null;
          website?: string | null;
          // Contact
          contact_email?: string | null;
          phone?: string | null;
          // Social
          social_links?: Json | null;
          follower_count?: number | null;
          following_count?: number | null;
          profile_views?: number | null;
          // Crypto
          bitcoin_address?: string | null;
          lightning_address?: string | null;
          bitcoin_public_key?: string | null;
          lightning_node_id?: string | null;
          bitcoin_balance?: number | null;
          lightning_balance?: number | null;
          // Status & Verification
          verification_status?: string | null;
          verification_level?: string | null;
          is_verified?: boolean | null;
          kyc_status?: string | null;
          verification_data?: Json | null;
          verification_badge?: string | null;
          status?: string | null;
          // Activity
          campaign_count?: number | null;
          total_raised?: number | null;
          total_donated?: number | null;
          last_login_at?: string | null;
          last_active_at?: string | null;
          login_count?: number | null;
          // Preferences
          language?: string | null;
          currency?: string | null;
          theme_preferences?: Json | null;
          custom_css?: string | null;
          profile_color?: string | null;
          profile_badges?: Json | null;
          payment_preferences?: Json | null;
          preferences?: Json | null;
          privacy_settings?: Json | null;
          metadata?: Json | null;
          // Onboarding
          onboarding_completed?: boolean | null;
          profile_completed_at?: string | null;
          terms_accepted_at?: string | null;
          privacy_policy_accepted_at?: string | null;
          two_factor_enabled?: boolean | null;
          // Timestamps
          created_at?: string;
          updated_at?: string;
        };
      };
      // Add other tables here as needed...
      [key: string]: {
        Row: { [key: string]: any };
        Insert: { [key: string]: any };
        Update: { [key: string]: any };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}



