-- ROLLBACK: 20251013072134_fix_profiles_complete
-- Generated: 2025-12-04T12:37:00.392Z
-- Source: 20251013072134_fix_profiles_complete.sql

ALTER TABLE IF DROP COLUMN IF EXISTS IF;
ALTER TABLE IF DROP COLUMN IF EXISTS IF;
ALTER TABLE IF DROP COLUMN IF EXISTS IF;
ALTER TABLE IF DROP COLUMN IF EXISTS IF;
ALTER TABLE IF DROP COLUMN IF EXISTS IF;
ALTER TABLE IF DROP COLUMN IF EXISTS IF;
ALTER TABLE IF DROP COLUMN IF EXISTS IF;
ALTER TABLE IF DROP COLUMN IF EXISTS IF;
ALTER TABLE IF DROP COLUMN IF EXISTS IF;
DROP FUNCTION IF EXISTS public;
-- MANUAL: Review data inserted into public
DROP FUNCTION IF EXISTS public;
DROP TRIGGER IF EXISTS set_updated_at ON public;
DROP FUNCTION IF EXISTS public;
ALTER TABLE public DROP CONSTRAINT IF EXISTS profiles_username_key;
ALTER TABLE public DROP CONSTRAINT IF EXISTS profiles_email_format;
ALTER TABLE public DROP CONSTRAINT IF EXISTS profiles_website_format;

-- Rollback completed: 20251013072134_fix_profiles_complete